Repository lazd/coronadatascraper, pull requests merged in 2020-03, with the labels that each got.

#104 [patch] add linting, and remove lint
  .eslintrc.json
  .github/workflows/test.yml
  cli.js
  index.js
  lib/cliArgs.js
  lib/datetime.js
  lib/datetime.test.js
  lib/fetch.js
  lib/fs.js
  lib/parse.js
  lib/parse.test.js
  lib/rules.js
  lib/stringify.js
  lib/transform.js
  lib/transform.test.js
  package.json
  scrapers.js
  site/index.html
  tasks/findFeatures.js
  tasks/findPopulations.js
  tasks/scrapeData.js
  tasks/writeData.js
  timeseries.js
  tools/mapJHUCounties.js
  yarn.lock
Labels: critical

#321 fix: handle network errors
  src/events/crawler/lib/fetch.js
  src/events/crawler/scrapers/USA/KS/index.js
Labels: bug, critical

#472 Made a few design changes
  .gitignore
  public/index.html
Labels: enhancement, website
